# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\"B\n\nExpression\x12\x10\n\x08operand1\x18\x01 \x01(\x02\x12\x10\n\x08operand2\x18\x02 \x01(\x02\x12\x10\n\x08operator\x18\x03 \x01(\t2:\n\x11\x45xecuteExpression\x12%\n\x07\x45xecExp\x12\x0b.Expression\x1a\x0b.Expression\"\x00\x62\x06proto3')
)




_EXPRESSION = _descriptor.Descriptor(
  name='Expression',
  full_name='Expression',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operand1', full_name='Expression.operand1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operand2', full_name='Expression.operand2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operator', full_name='Expression.operator', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Expression'] = _EXPRESSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Expression = _reflection.GeneratedProtocolMessageType('Expression', (_message.Message,), dict(
  DESCRIPTOR = _EXPRESSION,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Expression)
  ))
_sym_db.RegisterMessage(Expression)



_EXECUTEEXPRESSION = _descriptor.ServiceDescriptor(
  name='ExecuteExpression',
  full_name='ExecuteExpression',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=88,
  serialized_end=146,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExecExp',
    full_name='ExecuteExpression.ExecExp',
    index=0,
    containing_service=None,
    input_type=_EXPRESSION,
    output_type=_EXPRESSION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXECUTEEXPRESSION)

DESCRIPTOR.services_by_name['ExecuteExpression'] = _EXECUTEEXPRESSION

# @@protoc_insertion_point(module_scope)
