# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class ExecuteExpressionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExecExp = channel.unary_unary(
        '/ExecuteExpression/ExecExp',
        request_serializer=calculator__pb2.Expression.SerializeToString,
        response_deserializer=calculator__pb2.Expression.FromString,
        )


class ExecuteExpressionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ExecExp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExecuteExpressionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExecExp': grpc.unary_unary_rpc_method_handler(
          servicer.ExecExp,
          request_deserializer=calculator__pb2.Expression.FromString,
          response_serializer=calculator__pb2.Expression.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ExecuteExpression', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
